import Footer from '@/components/Footer';
import LoginHeader from '@/components/LoginHeader';
export const metadata = {
  title: 'Login Meta Title',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body style={{ backgroundColor: '#ccc' }}>
        <LoginHeader />
        {children}
        <Footer />
      </body>
    </html>
  );
}
