export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body>
        <header
          style={{
            backgroundColor: 'skyblue',
            textAlign: 'center',
            padding: '30px',
            marginBottom: '30px',
          }}
        >
          <p>This is header</p>
        </header>
        {children}
        <footer
          style={{
            backgroundColor: 'lightblue',
            textAlign: 'center',
            padding: '30px',
            marginTop: '30px',
          }}
        >
          <p>This is footer</p>
        </footer>
      </body>
    </html>
  );
}
