export const metadata = {
  title: {
    absolute: 'Forgot Password',
  },
  description: 'Generated by Next.js',
};
const ForgotPassword = () => {
  return (
    <div>
      <h1>Forgot Password</h1>
    </div>
  );
};

export default ForgotPassword;
