export const metadata = {
  title: 'User Registration',
  description: 'Generated by Next.js',
};

const Register = () => {
  return (
    <div>
      <h1>Register Page</h1>
    </div>
  );
};

export default Register;
